branches:
  only:
    - master
    - develop
    - "/^[0-9\\.]+$/"
sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.9.4
os:
  - linux
env:
  global:
    - GOX_FLAGS="-arch amd64"
    - GOX_OS="linux darwin windows"
addons:
  apt:
    packages:
      - python-virtualenv
before_install:
  - umask 022
  - mkdir -p $HOME/gopath/src/github.com/uphy/commandbeat/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/uphy/commandbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/uphy/commandbeat/
  - cd $HOME/gopath/src/github.com/uphy/commandbeat/
install:
  - true
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CC_FILENAME="test-reporter-latest-darwin-amd64"; else CC_FILENAME="test-reporter-latest-linux-amd64"; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/$CC_FILENAME > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - if [ "$TRAVIS_TAG" == "" ]; then make ci; else make package; fi
after_script:
  - ./testcoverage.sh
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "/home/travis/gopath/src/github.com/uphy/commandbeat/build/upload/*"
  overwrite: true
  on:
    tags: true
notifications:
  slack:
    secure: zPv73PWfvVKBSnyw2+4G4zxXD3PU1J1CX493RIf2NShLPzPIsmXeKavfTbky5Yg2oaoj+9HMD3w/Mm11HJwr5BPl7oBmbZ3AI3sbOgjakshnEJ+tRi/j6pKhNFAgCBbfXlFUnzXt4HuN5zVojiHJXZhVz00lX4d9gbGzfAesI2QUEYeT+7T1ZdF0bLGfZ0QZjSJu2WMaNu5u/0q2+lEZu2rSJ72D0+Bfi0e8SB+vzewKwmVuR8dQli9U0YOW53BC9EI1duHjGRqsBqkkQGVUf8mvIwqBqV06vS5KfYN2TnT6ZzVgDnWuSmI8DSwrwAc3EpM3KqrwOWsibEXAporOWbyKWDuz49VvzvDE5G6LdE1K+NIuXTcOU0T5NVlqp/SG4N+Xl8kFy0TICo+GJ0bJc7RU/RJ1A6AD+rh3Xk91GG8i1XN8bDuvW4CLIH8jGxfok8SREftAhkFhJbICvit1eATsK9XxjV07Si9jSaRnlKqVwlMvZ1x6i1+ovf3dR0iHqaLQOnBSs0NDYm5y4KgXLV2jQHAWJPrAtXClI5FOBzPi82QMWHNs4A674Wdk3MLkqMwTyNCPcxcAdn9ypVI1/wVzhWAA8CGnm53QGtbx5GQi4IO8Yuu6jFzlbYRxrXfbiMG40riL9UlDWsp39duobro9CVsW/uDs+mbkOE+xf7I=
