version: "3"

services:
  commandbeat:
    image: uphy/commandbeat:0.0.4
    volumes:
      - "./commandbeat.yml:/etc/commandbeat/commandbeat.yml"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    environment:
      - 'http.host=0.0.0.0'
      - 'transport.host=127.0.0.1'
    ports:
      - '127.0.0.1:9200:9200'
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    ports:
      - '127.0.0.1:5601:5601'
    depends_on:
      - 'elasticsearch'